#===== NeedTown - Config =====#
#~~~~ Made by jacklin213 ~~~~#

# Integrate with Towny? (Currently very buggy USE AT OWN RISK)
TownyIntegration: false

# NeedTown Prefix
PluginPrefix: '<red>[<aqua>Need<yellow>Town<red>]'

# Set this to true if you want to use custom messsages
CustomNeedTownMessage: true

# Use Cooldowns: true / false
Cooldowns: true
# In seconds
Cooldown-time: 30
# Cooldown message:
Cooldown-Message: '<red>너무 자주 입력할 수 없습니다!'

# Custom message
# Put '%p' where you want the player name to appear
# To use color put the color inbetween brackets like this '<red>' before your message

# Example:

#Message: '<gold>%p <green>needs a town/city! <red>Town Owners <green>plz be sure to invite <gold>%p <aqua>!'
Message: '<gold>%p <aqua>님이 마을에 들어가고 싶어합니다! <red>촌장님께서는 <gold>%p <aqua>를 해주세요!'

# Remeber to only have 1 message. If you have 2 messages it will read it as a error and send you the default message

# Plugin/config Copyright 2012 NeedTown Team
