name: NeedTown
version: 1.0
main: me.BMX_ATVMAN14.bukkit.NeedTown.NeedTown
description: Need a town? Just ask for it!
commands:
  needtown:
    description:
    permission: needtown.use
    aliases: []

permissions:
  needtown.*:
    description: Allows use of all needtown commands
    default: op
    children:
      needtown.use: true
      needtown.setmessage: true
  needtown.use:
    description: Allows people use needtown
    default: op
  needtown.setmessage:
    description: Allows people to set message
    default: op