name: NeedTown
version: 1.0
main: me.BMX_ATVMAN14.bukkit.NeedTown.NeedTown
description: Need a town? Just ask for it!
commands:
  needtown:
    description: Allows people to use the NeedTown command
    permission: needtown.use
    aliases: nt
    usage: The correct usage is /needtown or /nt
  t:
    description: test command

permissions:
  needtown.*:
    description: Allows use of all needtown commands
    default: op
    children:
      needtown.use: true
  needtown.use:
    description: Allows people use needtown
    default: op
