name: NeedTown
version: 2.5
main: me.jacklin213.needtown.NeedTown
description: Need a town? Just ask for it!
author: BMX_ATVMAN14
authors: [BMX_ATVMAN14, jacklin213]

commands:
  needtown:
    description: Allows people to use the NeedTown command
    permission: needtown.use
    aliases: nt
    usage: The correct usage is /needtown or /nt

permissions:
  needtown.*:
    description: Allows use of all needtown commands
    default: op
    children:
      needtown.use: true
      needtown.reload: true
      needtown.op: true
  needtown.op:
    description: Allows use Most of the needtown commands
    default: op
    children:
      needtown.use: true
      needtown.reload: true
  needtown.use:
    description: Allows people use needtown
    default: true
  needtown.reload:
    description: Allows people to reload config
    default: op
  
